config/routes.rb
Rails.application.routes.draw do
  # HW4: tasks are now nested under lists
  resources :lists, except: :show do
    resources :tasks
  end

  # HW4: list/show automatically shows tasks
  get 'lists/:list_id', to: redirect('/lists/%{list_id}/tasks'), constraints: { :list_id => /\d+/ }

  # HW5: add our users paths
  resources :users
  post 'login/:id', to: "users#login"
  post 'logout', to: "users#logout"

  root to: "users#index"
end

app/models/list.rb
class List < ActiveRecord::Base
  # HW4: set up association and validations
  validates :name, presence: true
  has_many :tasks, :dependent => :destroy

  # HW5: set up association to user
  belongs_to :user
  validates :user, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :name, presence: true

  # HW1: ensure completed is falsy on create at the model level
  validates :completed, absence: true, on: :create

  # HW4: set up association
  belongs_to :list
  validates :list, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # HW5: set up association and validations
  validates :name, presence: true
  has_many :lists, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # HW5: lock down all controllers by default
  before_filter :require_login

  private

  def require_login
    @current_user = User.find_by_id(session[:current_user_id])
    unless @current_user
      redirect_to users_path
    end
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    # HW5: limit lists to owned by currently logged in user
    @lists = List.where(user: @current_user)
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.where('id = ? AND user_id = ?', params[:id], @current_user.id).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :user_id)
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_list

  # GET /tasks
  # GET /tasks.json
  def index
    # HW4: only display the tasks we need
    @tasks = Task.where(list: @list)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to list_tasks_path(@list), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to list_tasks_path(@list), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to list_tasks_url(@list), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # HW4: we'll need to know which list we're working with
    def set_list
      @list = List.where('id = ? AND user_id = ?', params[:list_id], @current_user.id).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :completed, :list_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login
  before_action :set_user, only: [:show, :edit, :update, :destroy, :login]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # HW5: add our completely insecure auth methods
  def login
    msg = 'User could not be logged in'
    if @user
      session[:current_user_id] = @user.id
      msg = "#{@user.name} was successfully logged in"
    end

    respond_to do |format|
      format.html { redirect_to lists_path, notice: msg }
      format.json { head :no_content }
    end
  end

  def logout
    reset_session
    msg = 'User was successfully logged out'

    respond_to do |format|
      format.html { redirect_to users_url, notice: msg }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id]) if params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Todo
    =stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    =javascript_include_tag 'application', 'data-turbolinks-track' => true
    =csrf_meta_tags
  %body
    =yield

app/views/lists/_form.html.haml
= form_for @list do |f|
  - if @list.errors.any?
    #error_explanation
      %h2= "#{pluralize(@list.errors.count, "error")} prohibited this list from being saved:"
      %ul
        - @list.errors.full_messages.each do |msg|
          %li= msg

  -# HW5: save currently logged in user
  =f.hidden_field :user_id, :value => @current_user.id

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/lists/edit.html.haml
%h1 Editing list

= render 'form'

= link_to 'Show', @list
\|
= link_to 'Back', lists_path

app/views/lists/index.html.haml
%h1= "Listing lists:  logged in as #{@current_user.name}"

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @lists.each do |list|
      %tr
        %td= list.name
        %td= link_to 'Show', list
        %td= link_to 'Edit', edit_list_path(list)
        %td= link_to 'Destroy', list, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to "New List", new_list_path
= link_to "Log out", 'logout', :method => :post

app/views/lists/new.html.haml
%h1 New list

= render 'form'

= link_to 'Back', lists_path

app/views/lists/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @list.name

= link_to 'Edit', edit_list_path(@list)
\|
= link_to 'Back', lists_path

app/views/tasks/_form.html.haml
-if @task.errors.any?
  #error_explanation
    %h2="#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
    %ul
      -@task.errors.full_messages.each do |msg|
        %li= msg

.field
  =f.label :name
  =f.text_field :name

-# HW1: hide checkbox on create
-unless @task.new_record?
  .field
    =f.label :completed
    =f.check_box :completed

.actions
  =f.submit 'Save'

app/views/tasks/edit.html.haml
%h1 Editing task

=form_for @task, url: [@list, @task], html: { method: :put } do |f|
  =render 'form', f: f

=link_to 'Show', [@list, @task]
\|
=link_to 'Back', list_tasks_path(@list)

app/views/tasks/index.html.haml
-# HW4: added List name to clarify which list we're in
%h1=@list.name

-# HW2: clicking these links toggle the rows we want on the frontend. IMHO, no need for round trip to server for this use case
-# HW3: added the 'show_by_default' data element which sets the initial value
=link_to "%%TOGGLE%% Incomplete Tasks", "#", class: "tasks_toggle_link", data: {needle: '.tasktable tr.incomplete', show_by_default: true}
=link_to "%%TOGGLE%% Complete Tasks", "#", class: "tasks_toggle_link", data: {needle: '.tasktable tr.complete', show_by_default: false}

-# HW2: hijack the links as soon as the page loads
:javascript
  $(document).ready(function() {
    hijackToggleLinks();
  });

%br
%br

%table.tasktable
  %thead
    %tr
      %th.name Name
      %th.completed Completed
      %th
      %th
      %th

  %tbody
    - @tasks.each do |task|
      -# HW2: seeding the row class to make it easier for the filters to find
      %tr{:class => "#{task.completed ? 'complete' : 'incomplete'}"}
        %td=task.name
        %td=(task.completed == true)
        %td=link_to 'Show', [@list, task]
        %td=link_to 'Edit', [:edit, @list, task]
        %td=link_to 'Destroy', [@list, task], :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

=link_to 'Add a task', new_list_task_path(@list)

-# HW4: so we can get back to lists
=link_to 'Back to Lists', lists_path

%br

app/views/tasks/new.html.haml
%h1 Create a task
-# HW4: needed to split out the form to specify the url
=form_for @task, url: list_tasks_path(@list), html: { method: :post } do |f|
  -# HW4: need to add the list_id hidden field to associate the new task
  =f.hidden_field :list_id, :value => params[:list_id]
  =render 'form', f: f

=link_to 'Back', list_tasks_path(@list)

app/views/tasks/show.html.haml
%p#notice=notice

%p
  %b Name:
  =@task.name
%p
  %b Completed:
  =@task.completed

=link_to 'Edit', edit_list_task_path(@list, @task)
\|
=link_to 'Back', list_tasks_path(@list)

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :password
    = f.text_field :password
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%p#notice= notice

%table
  %thead
    %tr
      %th Name
      %th Password
      %th
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.password
        %td= link_to 'Login', "login/#{user.id}", :method => :post
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path
= link_to 'Logout', 'logout', :method => :post

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Password:
  = @user.password

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path